import type { Metadata } from 'next'
import './globals.css'
import { MobileNavigation } from '@/components/usable/mobile-navigation'
import { DesktopNavigation } from '@/components/usable/desktop-navigation'
import { navigationConfig } from '@/config/navigation'
import { Lato } from 'next/font/google'

const lato = Lato({
  variable: '--font-oswald',
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable} antialiased min-h-screen flex flex-col gap-10`}>
        <DesktopNavigation items={navigationConfig.mainNav} />
        <main className="flex-1 mb-36 space-y-20 pl-5 md:px-5">{children}</main>
        <MobileNavigation />
      </body>
    </html>
  )
}
