import type { Metadata } from "next"

import "./globals.css"

import { Lato } from "next/font/google"
import { ClerkProvider, SignedIn, SignedOut, SignInButton, SignUpButton, UserButton } from "@clerk/nextjs"

import { navigationConfig } from "@/config/navigation"
import { DesktopNavigation } from "@/components/usable/desktop-navigation"
import { MobileNavigation } from "@/components/usable/mobile-navigation"

const lato = Lato({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${lato.variable} flex min-h-screen flex-col antialiased`}>
          <header className="flex h-20 items-center justify-end gap-4">
            <SignedOut>
              <SignInButton />
              <SignUpButton />
            </SignedOut>
            <SignedIn>
              <DesktopNavigation items={navigationConfig.mainNav} />
            </SignedIn>
          </header>
          <main className="flex-1">{children}</main>
          <MobileNavigation />
        </body>
      </html>
    </ClerkProvider>
  )
}
